### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by zu** [swissspidy/preferred-languages#24]
Ich weiss nicht, ob das mit einem anderen Plugin zu tun hat.
Es geschah aber bei der Aktivierung von preferred languages:

```
Fatal error: Uncaught Error: Call to a member function get() on null in [path]/wp-content/plugins/preferred-languages-master/inc/functions.php:468 Stack trace: #0 [path]/wp-includes/class-wp-hook.php(298): preferred_languages_filter_gettext('Product by User', 'Product by User', 'woocommerce-jet...') #1 [path]/wordpress/wp-includes/plugin.php(203): WP_Hook->apply_filters('Product by User', Array) #2 [path]/wordpress/wp-includes/l10n.php(134): apply_filters('gettext', 'Product by User', 'Product by User', 'woocommerce-jet...') #3 [path]/wordpress/wp-includes/l10n.php(202): translate('Product by User', 'woocommerce-jet...') #4 [path]/wp-content/plugins/woocommerce-jetpack/includes/shortcodes/class-wcj-products-add-form in [path]/wp-content/plugins/preferred-languages-master/inc/functions.php on line 468
```

**Comment by swissspidy** [comment]
Yeah I can confirm this.

**Comment by swissspidy** [comment]
Should be fixed now. Will release 1.2.0 soon.
